### ISSUE TITLE
Alert System

### ISSUE THREAD

**Issue by baudday** [baudday/crimestream#1]
I'd like to create an alert system where a user can submit their information to receive alerts when something serious (robbery, stabbing, etc) happens in their neighborhood.

**Comment by 82rules** [comment]
Is there any preference for how you want to handle neighborhood, a radius around lat long? 
Well need to convert lat-longs to true POINT or at least floats to do the geo math

**Comment by baudday** [comment]
Yeah, I was thinking 1-2 mile radius should be sufficient for a user to be alerted

**Comment by groovecoder** [comment]
We already added [Tulsa to citygram](https://www.citygram.org/tulsa) at a previous Code for Tulsa event, and Code for America pays for the citygram text messaging fees for us. So, integrating with citygram could be an easy way to do this.

**Comment by baudday** [comment]
Oh man, this looks perfect

**Comment by groovecoder** [comment]
Yeah, come to CodeAcross and someone can help you with it.

**Comment by baudday** [comment]
Submitted a PR to add these alerts to Tulsa Citygram: https://github.com/citygram/citygram-services/pull/55
